In [2]:
from itertools import permutations
import pandas as pd

def generate_matchups(teams_df):
 
    teams = teams_df["name"].tolist()
    matchups = list(permutations(teams, 2)) 

    match_df = pd.DataFrame(matchups, columns=["team1", "team2"])
    return match_df

qualified_teams = pd.read_csv("qualified.csv")
match_df = generate_matchups(qualified_teams)
match_df.head()


team1 team2
0   RUS   KSA
1   RUS   EGY
2   RUS   URU
3   RUS   POR
4   RUS   ESP

In [3]:
import pandas as pd
def map_team_features(match_df, team_stats):

    team1_stats = team_stats.drop_duplicates(subset=["team1"]).set_index("team1")
    team2_stats = team_stats.drop_duplicates(subset=["team2"]).set_index("team2")  

    team1_stats = team1_stats.add_suffix("_team1")
    team2_stats = team2_stats.add_suffix("_team2")

    match_df = match_df.merge(team1_stats, left_on="team1", right_index=True, how="left")


    match_df = match_df.merge(team2_stats, left_on="team2", right_index=True, how="left")

    match_df["team1Home"] = match_df["team1"] == "RUS"
    match_df["team2Home"] = match_df["team2"] == "RUS"
    match_df["neutralVenue"] = ~(match_df["team1Home"] | match_df["team2Home"])
    match_df["friendly"] = False
    match_df["qualifier"] = False
    match_df["finaltourn"] = True

    required_columns = [
        "team1", "team2", "team1Home", "team2Home", "neutralVenue", "friendly", "qualifier", "finaltourn", "team1_win_rate_10_team1", 
        "team1_loss_rate_10_team1", "team1_draw_rate_10_team1", "team1_goal_diff_avg_10_team1",
        "team1_confed_form_10_team1", "team1_win_rate_20_team1", "team1_loss_rate_20_team1",
        "team1_draw_rate_20_team1", "team1_goal_diff_avg_20_team1", "team1_confed_form_20_team1",
        "team1_win_rate_30_team1", 
        "team1_loss_rate_30_team1", "team1_draw_rate_30_team1", "team1_goal_diff_avg_30_team1",
        "team1_confed_form_30_team1", "team1_win_rate_40_team1", "team1_loss_rate_40_team1",
        "team1_draw_rate_40_team1", "team1_goal_diff_avg_40_team1", "team1_confed_form_40_team1",
        "team1_win_rate_50_team1", 
        "team1_loss_rate_50_team1", "team1_draw_rate_50_team1", "team1_goal_diff_avg_50_team1",
        "team1_confed_form_50_team1",
        
        "team2_win_rate_10_team2", "team2_loss_rate_10_team2", "team2_draw_rate_10_team2",
        "team2_goal_diff_avg_10_team2", "team2_confed_form_10_team2", "team2_win_rate_20_team2",
        "team2_loss_rate_20_team2", "team2_draw_rate_20_team2", "team2_goal_diff_avg_20_team2",
        "team2_confed_form_20_team2",
        "team2_win_rate_30_team2", "team2_loss_rate_30_team2", "team2_draw_rate_30_team2",
        "team2_goal_diff_avg_30_team2", "team2_confed_form_30_team2", "team2_win_rate_40_team2",
        "team2_loss_rate_40_team2", "team2_draw_rate_40_team2", "team2_goal_diff_avg_40_team2",
        "team2_confed_form_40_team2",
        "team2_win_rate_50_team2", "team2_loss_rate_50_team2", "team2_draw_rate_50_team2",
        "team2_goal_diff_avg_50_team2", "team2_confed_form_50_team2"
    ]


    rename_columns = {col: col.replace("_team1_team1", "_team1").replace("_team2_team2", "_team2") for col in match_df.columns}
    match_df = match_df.rename(columns=rename_columns)

   
    match_df = match_df[required_columns]

    return match_df
df=pd.read_csv('updated2.csv')
df = df.sort_values(by="date", ascending=False)
match_df = map_team_features(match_df, df)
match_df.head()


team1 team2  team1Home  team2Home  neutralVenue  friendly  qualifier  \
0   RUS   KSA       True      False         False     False      False   
1   RUS   EGY       True      False         False     False      False   
2   RUS   URU       True      False         False     False      False   
3   RUS   POR       True      False         False     False      False   
4   RUS   ESP       True      False         False     False      False   

   finaltourn  team1_win_rate_10_team1  team1_loss_rate_10_team1  ...  \
0        True                      0.6                       0.3  ...   
1        True                      0.6                       0.3  ...   
2        True                      0.6                       0.3  ...   
3        True                      0.6                       0.3  ...   
4        True                      0.6                       0.3  ...   

   team2_win_rate_40_team2  team2_loss_rate_40_team2  \
0                    0.325                     0.375   
1                    0.450                     0.350   
2                    0.450                     0.375   
3                    0.225                     0.600   
4                    0.075                     0.750   

   team2_draw_rate_40_team2  team2_goal_diff_avg_40_team2  \
0                     0.300                         0.350   
1                     0.200                        -0.175   
2                     0.175                        -0.200   
3                     0.175                         0.650   
4                     0.175                         1.425   

   team2_confed_form_40_team2  team2_win_rate_50_team2  \
0                       0.325                     0.32   
1                       0.375                     0.38   
2                       0.425                     0.42   
3                       0.225                     0.22   
4                       0.100                     0.10   

   team2_loss_rate_50_team2  team2_draw_rate_50_team2  \
0                      0.42                      0.26   
1                      0.36                      0.26   
2                      0.34                      0.24   
3                      0.58                      0.20   
4                      0.70                      0.20   

   team2_goal_diff_avg_50_team2  team2_confed_form_50_team2  
0                          0.36                        0.28  
1                          0.02                        0.36  
2                         -0.14                        0.46  
3                          0.64                        0.22  
4                          1.26                        0.08  

[5 rows x 58 columns]

In [4]:
match_df['friendly']=0
match_df['qualifier']=0
match_df['team1Home']=0
match_df['team2Home']=0
match_df['neutralVenue']=1
match_df['finaltourn']=1
match_df.head()

team1 team2  team1Home  team2Home  neutralVenue  friendly  qualifier  \
0   RUS   KSA          0          0             1         0          0   
1   RUS   EGY          0          0             1         0          0   
2   RUS   URU          0          0             1         0          0   
3   RUS   POR          0          0             1         0          0   
4   RUS   ESP          0          0             1         0          0   

   finaltourn  team1_win_rate_10_team1  team1_loss_rate_10_team1  ...  \
0           1                      0.6                       0.3  ...   
1           1                      0.6                       0.3  ...   
2           1                      0.6                       0.3  ...   
3           1                      0.6                       0.3  ...   
4           1                      0.6                       0.3  ...   

   team2_win_rate_40_team2  team2_loss_rate_40_team2  \
0                    0.325                     0.375   
1                    0.450                     0.350   
2                    0.450                     0.375   
3                    0.225                     0.600   
4                    0.075                     0.750   

   team2_draw_rate_40_team2  team2_goal_diff_avg_40_team2  \
0                     0.300                         0.350   
1                     0.200                        -0.175   
2                     0.175                        -0.200   
3                     0.175                         0.650   
4                     0.175                         1.425   

   team2_confed_form_40_team2  team2_win_rate_50_team2  \
0                       0.325                     0.32   
1                       0.375                     0.38   
2                       0.425                     0.42   
3                       0.225                     0.22   
4                       0.100                     0.10   

   team2_loss_rate_50_team2  team2_draw_rate_50_team2  \
0                      0.42                      0.26   
1                      0.36                      0.26   
2                      0.34                      0.24   
3                      0.58                      0.20   
4                      0.70                      0.20   

   team2_goal_diff_avg_50_team2  team2_confed_form_50_team2  
0                          0.36                        0.28  
1                          0.02                        0.36  
2                         -0.14                        0.46  
3                          0.64                        0.22  
4                          1.26                        0.08  

[5 rows x 58 columns]

In [5]:
match_df = match_df.rename(columns=lambda x: x.replace("_team1", "").replace("_team2", ""))
match_df.head()

team1 team2  team1Home  team2Home  neutralVenue  friendly  qualifier  \
0   RUS   KSA          0          0             1         0          0   
1   RUS   EGY          0          0             1         0          0   
2   RUS   URU          0          0             1         0          0   
3   RUS   POR          0          0             1         0          0   
4   RUS   ESP          0          0             1         0          0   

   finaltourn  team1_win_rate_10  team1_loss_rate_10  ...  team2_win_rate_40  \
0           1                0.6                 0.3  ...              0.325   
1           1                0.6                 0.3  ...              0.450   
2           1                0.6                 0.3  ...              0.450   
3           1                0.6                 0.3  ...              0.225   
4           1                0.6                 0.3  ...              0.075   

   team2_loss_rate_40  team2_draw_rate_40  team2_goal_diff_avg_40  \
0               0.375               0.300                   0.350   
1               0.350               0.200                  -0.175   
2               0.375               0.175                  -0.200   
3               0.600               0.175                   0.650   
4               0.750               0.175                   1.425   

   team2_confed_form_40  team2_win_rate_50  team2_loss_rate_50  \
0                 0.325               0.32                0.42   
1                 0.375               0.38                0.36   
2                 0.425               0.42                0.34   
3                 0.225               0.22                0.58   
4                 0.100               0.10                0.70   

   team2_draw_rate_50  team2_goal_diff_avg_50  team2_confed_form_50  
0                0.26                    0.36                  0.28  
1                0.26                    0.02                  0.36  
2                0.24                   -0.14                  0.46  
3                0.20                    0.64                  0.22  
4                0.20                    1.26                  0.08  

[5 rows x 58 columns]

In [7]:

match_df.to_csv('sim.csv', index=False)

In [8]:
arg_bra_match = match_df[
    ((match_df["team1"] == "NGA") & (match_df["team2"] == "BRA"))
]
print(arg_bra_match)

    team1 team2  team1Home  team2Home  neutralVenue  friendly  qualifier  \
480   NGA   BRA          0          0             1         0          0   

     finaltourn  team1_win_rate_10  team1_loss_rate_10  ...  \
480           1                0.8                 0.2  ...   

     team2_win_rate_40  team2_loss_rate_40  team2_draw_rate_40  \
480              0.175                0.55               0.275   

     team2_goal_diff_avg_40  team2_confed_form_40  team2_win_rate_50  \
480                    1.25                 0.275               0.18   

     team2_loss_rate_50  team2_draw_rate_50  team2_goal_diff_avg_50  \
480                0.52                 0.3                    1.14   

     team2_confed_form_50  
480                  0.28  

[1 rows x 58 columns]


In [9]:
import joblib
encoder = joblib.load('encoder.joblib')


arg_bra_match["team1"] = encoder.transform(arg_bra_match["team1"])
arg_bra_match["team2"] = encoder.transform(arg_bra_match["team2"])

arg_bra_match.head()

C:\Users\mKayy\AppData\Local\Temp\ipykernel_16040\1829450150.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  arg_bra_match["team1"] = encoder.transform(arg_bra_match["team1"])
C:\Users\mKayy\AppData\Local\Temp\ipykernel_16040\1829450150.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  arg_bra_match["team2"] = encoder.transform(arg_bra_match["team2"])


team1  team2  team1Home  team2Home  neutralVenue  friendly  qualifier  \
480    136     28          0          0             1         0          0   

     finaltourn  team1_win_rate_10  team1_loss_rate_10  ...  \
480           1                0.8                 0.2  ...   

     team2_win_rate_40  team2_loss_rate_40  team2_draw_rate_40  \
480              0.175                0.55               0.275   

     team2_goal_diff_avg_40  team2_confed_form_40  team2_win_rate_50  \
480                    1.25                 0.275               0.18   

     team2_loss_rate_50  team2_draw_rate_50  team2_goal_diff_avg_50  \
480                0.52                 0.3                    1.14   

     team2_confed_form_50  
480                  0.28  

[1 rows x 58 columns]

In [10]:
import xgboost as xgb
import numpy as np
best_xgb = xgb.XGBClassifier()
best_xgb.load_model("best_xgb.json")
X_test = arg_bra_match
import numpy as np
def add_randomness(probabilities, noise_factor=0.05):

    noise = np.random.normal(0, noise_factor, probabilities.shape) 
    probabilities = probabilities + noise  
    probabilities = np.clip(probabilities, 0, 1)  
    probabilities /= probabilities.sum()  
    return probabilities

for i in range(99):
    prediction = best_xgb.predict(X_test)
    probabilities = best_xgb.predict_proba(X_test)[0]
    random_probs=add_randomness(probabilities)
    max_prob = np.max(random_probs) 
    max_index = np.argmax(random_probs)

    print(random_probs)

    if max_prob >= 0.5:
        pred=max_index
    else:
        pred=np.random.choice([0,1,2])
    outcome_map={0:'Draw', 1:'ARG', 2:'BRA'}
    print(outcome_map[pred])

[0.00819882 0.42421276 0.56758842]
BRA
[0.05140224 0.44981669 0.49878107]
ARG
[0.04850325 0.41851545 0.5329813 ]
BRA
[0.03298592 0.39037349 0.57664058]
BRA
[0.         0.46676404 0.53323596]
BRA
[0.         0.41916719 0.58083281]
BRA
[0.        0.4501321 0.5498679]
BRA
[0.07792501 0.44483307 0.47724192]
BRA
[0.         0.43176857 0.56823143]
BRA
[0.13357112 0.38815703 0.47827185]
ARG
[0.10257295 0.35077637 0.54665068]
BRA
[0.         0.43043152 0.56956848]
BRA
[0.02470379 0.42505323 0.55024298]
BRA
[0.04437349 0.44742993 0.50819659]
BRA
[0.         0.44040405 0.55959595]
BRA
[0.14871167 0.36260543 0.48868291]
BRA
[0.         0.43619902 0.56380098]
BRA
[0.06854678 0.42228    0.50917322]
BRA
[0.0184759  0.42762685 0.55389725]
BRA
[0.         0.39066053 0.60933947]
BRA
[0.         0.31562325 0.68437675]
BRA
[0.         0.43517193 0.56482807]
BRA
[0.         0.36419022 0.63580978]
BRA
[0.         0.49848906 0.50151094]
BRA
[0.         0.39181532 0.60818468]
BRA
[0.05630917 0.46136685 0.482